# Generated by Django 4.2 on 2024-12-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='The Name of the Service', max_length=300),
        ),
    ]
