# Generated by Django 4.2 on 2024-12-10 10:17

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tag', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='The Blog Title', max_length=100, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text="Blog's Meta Title", max_length=100, null=True)),
                ('meta_description', models.CharField(blank=True, help_text="Blog's Meta Description", max_length=100, null=True)),
                ('short_description', models.CharField(blank=True, help_text="Blog's Short Description", max_length=100, null=True)),
                ('sub_description', models.TextField(blank=True, help_text='Blog Sub Description', max_length=300, null=True)),
                ('description', models.TextField(help_text='Blog Content This field is deprecated', max_length=10000)),
                ('body', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True, verbose_name='Blog Content')),
                ('featured_image_mobile', models.ImageField(help_text='Background image for mobile', upload_to='', verbose_name='Thumbnail Image Mobile')),
                ('featured_image_desktop', models.ImageField(help_text='Background image for desktop', upload_to='', verbose_name='Thumbnail Image Desktop')),
                ('main_image_mobile', models.ImageField(blank=True, help_text='Main image for mobile', null=True, upload_to='', verbose_name='Main Image Mobile')),
                ('main_image_desktop', models.ImageField(blank=True, help_text='Main image for desktop', null=True, upload_to='', verbose_name='Main Image Desktop')),
                ('published_at', models.DateField(auto_now_add=True, help_text='Published Date')),
                ('read_time', models.PositiveIntegerField(default=0, help_text='The Blog read time automatically calculated after save')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured Blog?')),
                ('is_popular_blog', models.BooleanField(default=False, help_text='Popular Blog?')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(help_text='List the Blogs based on sort order')),
                ('slug', models.SlugField(help_text='The slug for the current blog')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with the blog', related_name='blogs', to='blog.tag')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('is_featured', 'sort_order')},
            },
        ),
    ]
